services:
  mysql:
    image: "${MYSQL_IMAGE}"
    restart: unless-stopped
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 5s
    volumes:
      - db-data:/var/lib/mysql:rw
    networks:
      - wordpress-network

  phpmyadmin:
    depends_on:
      - mysql
    image: "${PMA_IMAGE}"
    restart: unless-stopped
    ports:
      - "${PMA_EXTERNAL_PORT}:80"
    env_file: .env
    environment:
      PMA_HOST: mysql
      PMA_PORT: "${MYSQL_EXTERNAL_PORT}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - mysql
    image: "${WORDPRESS_IMAGE}"
    restart: unless-stopped
    ports:
      - "${WP_EXTERNAL_PORT}:80"
    env_file: .env
    user: 1000:1000
    environment:
      WORDPRESS_DB_HOST: mysql:${MYSQL_EXTERNAL_PORT}
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - wp-data:/var/www/html
      - ./wp-content/plugins/nirman-needs:/var/www/html/wp-content/plugins/nirman-needs
      - ./.backup:/var/www/html/.backup
      - ./wp-update-options.php:${SCRIPT_PATH}/wp-update-options.php:ro
      - ./wp-options.json:${CONFIG_PATH}/wp-options.json:ro

    networks:
      - wordpress-network

  wp-cli:
    depends_on:
      - mysql
    image: "${WPCLI_IMAGE}"
    env_file: .env
    user: 1000:1000
    environment:
      WORDPRESS_DEBUG: ${WP_DEBUG}
      WORDPRESS_DEBUG_LOG: ${WP_DEBUG_LOG}
      WORDPRESS_DB_HOST: mysql:${MYSQL_EXTERNAL_PORT}
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - wp-data:/var/www/html
      - ./bin/wp-custom-install.sh:/usr/local/bin/wp-custom-install:ro,Z
      - ./bin/nc-mysql.sh:/usr/local/bin/nc-mysql:ro,Z
      - ./bin/make-pot.sh:/usr/local/bin/make-pot:ro,Z
      - ./bin/wp-update-options.sh:/usr/local/bin/wp-update-options:ro,Z
      - ./wp-update-options.php:${SCRIPT_PATH}/wp-update-options.php:ro
      - ./wp-options.json:${CONFIG_PATH}/wp-options.json:ro
      - ./wp-content/plugins/nirman-needs/:/var/www/html/wp-content/plugins/nirman-needs
      - ./.backup:/var/www/html/.backup
    networks:
      - wordpress-network

volumes:
  db-data: null
  wp-data: null

networks:
  wordpress-network:
    driver: bridge
